[project]
name = "rl-voxel-agent-ppo-v1"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "compute-rhino3d>=0.12.2",
    "honeybee-core>=1.61.30",
    "honeybee-radiance>=1.66.184",
    "ladybug-geometry>=1.34.9",
    "lbt-recipes>=0.26.23",
    "stable-baselines3[extra]>=2.6.0",
    "tensorboard>=2.20.0",
    "torch==2.7.0",
]

[project.optional-dependencies]
cpu = ["torch==2.7.0"]
cu124 = ["torch==2.7.0"]
cu126 = ["torch==2.7.0"]
cu128 = ["torch==2.7.0"]

[tool.uv]
# The cpu and cuda extras are mutually exclusive, you can't use both at the same time
conflicts = [[{ extra = "cpu" }, {extra = "cu124"}, { extra = "cu126" }, {extra = "cu128"}]]

[tool.uv.sources]
# The torch, torchvision, and torchaudio packages are installed from the pytorch-cpu and pytorch-cu126, cu128 indexes
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu124", extra = "cu124" },
  { index = "pytorch-cu126", extra = "cu126" },
  { index = "pytorch-cu128", extra = "cu128" },
  { path = "../../Users/cawn069856/Downloads/torch-2.7.0+cu128-cp312-cp312-win_amd64.whl" }
]

[[tool.uv.index]]
# The pytorch-cpu index is used to install the torch, torchvision, and torchaudio packages
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true